#!/bin/bash
if [ ! -d "./config" ]; then
  cp -a "./_config/." "./config/"
fi

DIR="mml.app"
if [ -d "$DIR" ]; then
  cd $DIR
  git pull
  cd ..
else
  git clone --branch master https://github.com/we-kode/mml.app.git
fi
# replace icons
echo "Replacing icons"
cp -a "./config/icons/android/." "$DIR/android/app/src/main/res/"

# replace color schema
COLOR_SCHEME=./config/lib_color_schemes.g.dart
if test -f "$COLOR_SCHEME"; then
    echo "Replacing color scheme"
    cp "$COLOR_SCHEME" "$DIR/lib/lib_color_schemes.g.dart"
fi

# replace titles
echo "Replacing titles"
input="./config/app.cfg"
while IFS='=' read -r key value
do
  case $key in
	appTitle_en)
		sed -i -E "s/\"appTitle\": .*/\"appTitle\": \"$value\",/" "$DIR/lib/l10n/mml_app_en.arb"
		sed -i -E "s/\"    <string name=\"app_title\">.*<\/string>/\    <string name=\"app_title\">$value<\/string>/" "$DIR/android/app/src/main/res/values/strings.xml"
		;;
	appTitle_ru)
		sed -i -E "s/\"appTitle\": .*/\"appTitle\": \"$value\",/" "$DIR/lib/l10n/mml_app_ru.arb"
		sed -i -E "s/\"    <string name=\"app_title\">.*<\/string>/\    <string name=\"app_title\">$value<\/string>/" "$DIR/android/app/src/main/res/values-ru/strings.xml"
		;;
	appTitle_de)
		sed -i -E "s/\"appTitle\": .*/\"appTitle\": \"$value\",/" "$DIR/lib/l10n/mml_app_de.arb"
		sed -i -E "s/\"    <string name=\"app_title\">.*<\/string>/\    <string name=\"app_title\">$value<\/string>/" "$DIR/android/app/src/main/res/values-de/strings.xml"
		;;
	appTitle)
	    echo ""
		;;
	appId)
		sed -i -E "s/        applicationId \".*\"/        applicationId \"$value\"/" "$DIR/android/app/build.gradle"
		;;
	privacyUrl)
		sed -i -E "s/  final String privacyLink = \".*\";/  final String privacyLink = \"$value\";/" "$DIR/lib/view_models/settings.dart"
		;;
	legalInfofUrl)
		sed -i -E "s/  final String legalInfoLink = \".*\";/  final String legalInfoLink = \"$value\";/" "$DIR/lib/view_models/settings.dart"
		;;
	*)
		echo "Not known key: $key"
  esac
done < "$input"